version: "3.8"

services:
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --project=local --host-port=0.0.0.0:8085
    ports:
      - 8085:8085

volumes:
  es_data:
