name: Frontend Workflow
on:
  push:
    paths:
      - ".github/workflows/frontend-lint.yml"
      - "frontend/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16.13.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x

      - name: Install
        run: npm install
        working-directory: ./frontend

      - name: Lint
        run: npm run lint
        working-directory: ./frontend

      - name: Format Check
        run: npm run fmtcheck
        working-directory: ./frontend
